### ISSUE TITLE
kobo_df_download for XLS type

### ISSUE THREAD

**Issue by manhnguy** [asitav-sen/KoboconnectR#12]
Hi @asitav-sen, It was great and save me a lot of time with this download function. Thank you so much for your work. But now My boss asks me to have some repeat questions type and cannot be downloaded with csv type. Could you please consider making similar function that we can download and import to R with xls type. 
Thank you so much.
Mạnh

**Comment by asitav-sen** [comment]
Hi @manhnguy ,
Thanks. I will explore the options for the next version.

**Comment by rkopper610** [comment]
> Hi @asitav-sen, It was great and save me a lot of time with this download function. Thank you so much for your work. But now My boss asks me to have some repeat questions type and cannot be downloaded with csv type. Could you please consider making similar function that we can download and import to R with xls type. 
> 
> Thank you so much.
> 
> Mạnh

I came here with the exact same question. Thank you for creating this great package!

**Comment by manhnguy** [comment]
H @asitav-sen, In the meanwhile could you help me one thing. I'm using the kobo_export_create function to create a new export. Is there anyway that i can use that URL to delete the new export i just created? 
Thank you so much

**Comment by asitav-sen** [comment]
> H @asitav-sen, In the meanwhile could you help me one thing. I'm using the kobo_export_create function to create a new export. Is there anyway that i can use that URL to delete the new export i just created? Thank you so much

Hi @manhnguy ,
Try this.

`
httr::DELETE(url="TheURLtotheexport",
                      authenticate(user=uname, password =pwd), progress())
`

**Comment by manhnguy** [comment]
**I have tried these:** 
new_export_url <- kobo_export_create(url="kf.kobotoolbox.org", uname="", pwd="",
                               assetid="", type= "xls", all="false", 
                               include_grp = "true", grp_sep = "/", sleep = 3) #create new export
**then** 
DELETE(new_export_url, authenticate(user= "", password =""), progress())
**and i just get the result like this:**

Downloading: 950 B     Response [https://kf.kobotoolbox.org/private-media/manh_nguyen/exports/Contact_tracing_questionnaires_version1_-_latest_version_-_labels_-_2022-10-11-09-41-42.xlsx]
  Date: 2022-10-11 09:42
  Status: 403
  Content-Type: text/html; charset=utf-8
  Size: 1.89 kB

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
...
 but the export is still there

**Comment by asitav-sen** [comment]
@manhnguy Try this.

`
export_creator <- function(url="kobo.humanitarianresponse.info", uname="", pwd="",
                               assetid="", type= "csv", all="false", lang="_default",
                               hierarchy="false", include_grp="true",grp_sep="/", multi_sel="both",
                           fields=NULL, media_url="true", sub_ids= NULL,
                           qry=NULL, flatten="true", xls_typ_as_text="false", sleep=2){
  pre_export<- kobo_exports(url=url, uname=uname, pwd=pwd)
  pre_count<-ifelse(is.null(pre_export$count),0,pre_export$count)
  pre_time<-ifelse(is.null(pre_export$results$date_created),0,max(pre_export$results$date_created))

  fullurl<-paste0("https://",url,"/api/v2/assets/",assetid,"/exports/")
  task<-tryCatch(
    expr = {
      POST(fullurl, authenticate(uname, pwd),
           body=list(
             fields_from_all_versions= all,
             group_sep=grp_sep,
             hierarchy_in_labels = hierarchy,
             lang=lang,
             multiple_select=multi_sel,
             type=type,
             fields=fields,
             flatten= flatten,
             xls_types_as_text=xls_typ_as_text,
             #include_media_url=media_url,
             submission_ids=sub_ids,
             query=qry
           ),
           timeout(sleep*2))
    },
    error=function(x){
      print("There was some error")
      return(NULL)
    }
  )
  if(task$status_code==201) cat("Export instruction sent successfully. Waiting for result. \n")
  Sys.sleep(sleep)

  post_export<-kobo_exports(url=url, uname=uname, pwd=pwd)
  Sys.sleep(sleep*2)
  post_count<-post_export$count
  post_time<-max(post_export$results$date_created)


  if(post_time<=pre_time){
    cat("Execution in Progress...")
    Sys.sleep(sleep*2)
  }

  if(post_time<=pre_time){
    cat("Timeout")
    return(NULL)
  } else {
    if(post_export$results$status[post_count]=="error"){
      print(paste0("Did not execute. Encountered ",post_export$results$messages$error_type[post_count],". ",
                  post_export$results$messages$error[post_count],". \n"))
      return(NULL)
    } else {
      print("Export successful")

      if(is.na(post_export$results$result[post_count])){
        print("waiting..")
        Sys.sleep(sleep*5)
      }
      if(is.na(post_export$results$result[post_count])){
        print("Could not get export list")
        return(NULL)
      } else {
        print(post_export$results$result[post_count])
        new_url=post_export$results$result[post_count]
        uid=post_export$results$uid[post_count]
        created_list<-list(new_url,uid)
        return(created_list)
      }
    }
  }

}

new_export_details<-export_creator(url=url, uname=uname, pwd=pwd,
                                                 assetid=assetid, type= type, all=all, lang=lang,
                                                 hierarchy=hierarchy, include_grp=include_grp,grp_sep=grp_sep,
                                     multi_sel=multi_sel, fields=fields, media_url=media_url, sub_ids=sub_ids, sleep=sleep) #Enter the relevant values

  new_export_details<-export_creator(url=url, uname=uname, pwd=pwd,
                                                 assetid=assetid, type= "csv", all=all, lang=lang,
                                                 hierarchy=hierarchy, include_grp=include_grp,grp_sep=grp_sep,
                                     multi_sel=multi_sel, fields=fields, media_url=media_url, sub_ids=sub_ids, sleep=sleep)

  Sys.sleep(sleep)
  
  deleteact<-DELETE(url=paste0(url,"/api/v2/assets/",assetid,"/exports/",new_export_details[[2]],"/"),
                      authenticate(user=uname, password =pwd), progress())
                                     

`

**Comment by asitav-sen** [comment]
This can delete the export created using the function `export_creator`.
For details on how to delete it refer to the documents of kobotoolbox.
`https://{KF_URL}/api/v2/assets/{ASSET_UID}/exports`

**Comment by manhnguy** [comment]
I run this function.
new_export_details<-export_creator(url=url, uname="my_name", pwd="my_password",
                                   assetid="my_assetid", type= type, all=all, lang=lang,
                                   hierarchy=hierarchy, include_grp=include_grp,
                                   grp_sep=grp_sep,
                                   multi_sel=multi_sel, fields=fields, media_url=media_url, sub_ids=sub_ids, sleep=sleep) 
and result show:

Error in kobo_exports(url = url, uname = uname, pwd = pwd) : 
Forbidden (HTTP 403). Failed to extract export list..

do you know what i did wrong?

**Comment by asitav-sen** [comment]
I will have a look at it and get back to you at the earliest.

**Comment by manhnguy** [comment]
hi @asitav-sen ais, I found my mistake. I used your export creator function then I forgot to specify for my url and assetid in the DELETE function. It works now. Thank you so much for your support.

**Comment by asitav-sen** [comment]
Hi All,
I have added a new function `kobo_xls_dl()` to download xls format files and read them using `readxl::read_excel`. Please update your version (Use the dev version for the time being please) and try it. Please let me know if it helps.

**Comment by manhnguy** [comment]
Hi @asitav-sen, the function works. But for my form which I use repeating group, each repeating group will be export in different sheet in the excel file. how I choose the sheet to be imported to R?

**Comment by asitav-sen** [comment]
Hi @manhnguy 
Thanks. Can you please update the dev version and check now?

**Comment by manhnguy** [comment]
![Screen Shot 2022-10-18 at 10 28 16 AM](https://user-images.githubusercontent.com/87962720/196328908-45692cb5-a4d0-49d6-83bc-214d70ea5f93.png)
![Screen Shot 2022-10-18 at 10 29 21 AM](https://user-images.githubusercontent.com/87962720/196328988-92b7274b-3d32-40bb-af05-bcd73892e933.png)
Hi @asitav-sen, I uploaded the package as in the photo but I see the kobo_xls_dl() is still the same. Did I do something wrong?

**Comment by manhnguy** [comment]
when I try to use install_github("asitav-sen/KoboconnectR"), it shows errors as below
![Screen Shot 2022-10-18 at 11 03 11 AM](https://user-images.githubusercontent.com/87962720/196332881-245fb191-d9c3-4362-9b20-567afa0708bf.png)

**Comment by asitav-sen** [comment]
@manhnguy Sorry. I meant update the dev version and try.

**Comment by manhnguy** [comment]
I changed to R4.1.3 and first I install it says nothing has changed on Git and I use function force = TRUE as it suggest the package no longer work
<img width="1427" alt="Screen Shot 2022-10-18 at 13 24 32" src="https://user-images.githubusercontent.com/87962720/196352251-34e53efa-30e6-43e8-a1e0-2205bfc6c407.png">
<img width="1428" alt="Screen Shot 2022-10-18 at 13 25 06" src="https://user-images.githubusercontent.com/87962720/196352265-4b8deae6-97f9-4153-9570-3b1fd05b80b8.png">

**Comment by asitav-sen** [comment]
I updated the package about 37 minutes back. Perhaps you tried installing before the change was reflected in github?

**Comment by manhnguy** [comment]
I just updated my desktop to R 4.2.1 and it works, the function gives a list of the sheets. Thank you so much for your hard work and supportive. 
P/S my laptop still at 4.1.3 and it doesn't work :((

**Comment by asitav-sen** [comment]
@manhnguy Perhaps update R in your laptop as well?

**Comment by manhnguy** [comment]
Yes I will, the annoying thing is I have to ask IT for permission. but sure I have to do it anyway
