### ISSUE TITLE
Hi @mbk7162 ,

### ISSUE THREAD

**Issue by AbdulrahamanMusa** [asitav-sen/KoboconnectR#13]
Unable to use function kobo_df_download

Hi,  Asitav-sen
Many thanks for providing this awesome package,
I have come across the same issue however I was able to figure it out that is why I feel it is good to share so that others can benefit 
kindly the see method I apply below
data <- kobo_df_download(url="xxxxxxx",
                            uname="xxxxxxxx",
                            pwd="xxxxxxx",
                            assetid = "xxxxxx",
                            lang="_default")

I replace ( lang="English") to  lang="_default") and it works for me

Best regards

**Comment by asitav-sen** [comment]
Thanks @AbdulrahamanMusa !
