### ISSUE TITLE
Failure with kobo_df_download

### ISSUE THREAD

**Issue by rkopper610** [asitav-sen/KoboconnectR#14]
Hello,

I am having trouble downloading the survey results as a data frame. The process has worked well to date but I noticed it is not working-perhaps after the update? Previously, on occasion there were some time outs and failures when accessing exports but this seems a more definite failure. I tried increasing the sleep= amount but it still fails. I used dev version, cran version and then made a fresh download but no success.

Error is:
'''
Downloading: 7.2 kB     Export instruction sent successfully. Waiting for result. 
Downloading: 7.2 kB     Error in if (post_export$results$status[post_count] == "error") { : 
  missing value where TRUE/FALSE needed"
'''
Using function (with name, Id, and pw omitted)

'''
cm_dat <- KoboconnectR::kobo_df_download(uname = "name",
                                         pwd=pw, assetid = "id#",
                                         all="false", lang="_default",
                                         hierarchy="false", include_grp="true",grp_sep="/",fsep=";",
                                         multi_sel="both", media_url="true", fields=NULL, sub_ids=NULL, sleep=4)

'''

**Comment by asitav-sen** [comment]
Hi @rkopper610 ,
Sorry for the inconvenience. Unfortunately, I'm unable to reproduce the problem. Can we discuss this over a call? Perhaps you can show me what you are doing.

**Comment by rkopper610** [comment]
> Hi @rkopper610 ,
> 
> Sorry for the inconvenience. Unfortunately, I'm unable to reproduce the problem. Can we discuss this over a call? Perhaps you can show me what you are doing.

Hello,

I really appreciate your attention on this matter.
I think I was able to solve the issue by going onto KoboToolbox and manually deleting my exports as your usage.rmd vignette mentions on line 100.There were quite a bit of exports piled up.

I reran my code and it worked as before.

Thank you
