### ISSUE TITLE
Read existing exports to R using the URL from kobo_exports() function

### ISSUE THREAD

**Issue by manhnguy** [asitav-sen/KoboconnectR#3]
Hi, I wanted to use your package for my project. I find it would be very convenient for me if I can read or import the export dataset directly to R. I use the URL from kobo_exports() function but I could not do it:

For the excel file, it keep saying the path does not exist, but if I copy and paste the link to web it can be downloaded. 
library(openxlsx)
df <- read_excel("https://kf.kobotoolbox.org/private-media/manh_nguyen/exports/Contact_tracing_questionnaires_-_all_versions_-_False_-_2022-04-01-03-49-32.xlsx")
Error: `path` does not exist: ‘https://kf.kobotoolbox.org/private-media/manh_nguyen/exports/Contact_tracing_questionnaires_-_all_versions_-_False_-_2022-04-01-03-49-32.xlsx’

For the csv file it gives the error 403
library(readr)
df <- read_csv("https://kf.kobotoolbox.org/private-media/manh_nguyen/exports/Contact_tracing_questionnaires_-_all_versions_-_False_-_2022-04-15-02-36-24.csv")
Error in open.connection(3L, "rb") : HTTP error 403.

Thank you very much

**Comment by asitav-sen** [comment]
Hi @manhnguy,
Thanks.
The thing is, you cannot download directly from URL. It needs some authentication. Try this

```
df<-httr::GET("https://kf.kobotoolbox.org/private-media/manh_nguyen/exports/Contact_tracing_questionnaires_-_all_versions_-_False_-_2022-04-15-02-36-24.csv, httr::authenticate(user="userid", password ="password"))  
df<-httr::content(df, type="raw",encoding = "UTF-8") # Extract raw content
writeBin(df, "data.csv") # Write in local
my_data=read.csv("data.csv", sep=";")
```
Refer to [this article](https://blog.asitavsen.com/post/how-to-download-kobotoolbox-data-in-r/) for more details.
Please let me know it this solves your problem.

**Comment by manhnguy** [comment]
Great! Thank you so much for your quick response and all of your work. My problem has been solved.
