### ISSUE TITLE
kobo_export_create doesn't work

### ISSUE THREAD

**Issue by zxrey** [asitav-sen/KoboconnectR#5]
Hi @asitav-sen l see that you worked to doing the new version of Kobocollect, that is wonderful. l tried to get my xls, l update the version but l can't get when l put the commands

kobotools_api(
  url = "kobo.humanitarianresponse.info",
  simplified = TRUE,
  uname = "",
  pwd = "",
  encoding = "UTF-8"
)

then

kobotools_kpi_data(
  assetid,
  url = "kobo.humanitarianresponse.info",
  uname = "",
  pwd = "",
  encoding = "UTF-8"
)

and

kobo_export_create(
  url = "kobo.humanitarianresponse.info",
  uname = "",
  pwd = "",
  assetid = "",
  type = "csv",
  all = "false",
  lang = "_default",
  hierarchy = "false",
  include_grp = "true",
  grp_sep = "/",
  multi_sel = "both",
  fields = NULL,
  media_url = "true",
  sub_ids = NULL,
  qry = NULL,
  flatten = "true",
  sleep = 2
)

with the last one command, creates a empty value
![image](https://user-images.githubusercontent.com/68795117/170305198-702799cc-9825-4ff9-b4eb-153ed495cbb1.png)

Maybe did l something wrong

**Comment by asitav-sen** [comment]
Hi @zxrey ,
Please try changing the sleep parameter. It takes a while for the process to complete. Can you please increase the sleep value and check again?

**Comment by zxrey** [comment]
@asitav-sen l try changing the sleep timer until 120 and still does not work. By the way l want a xls type and for that l had to put **grp_sep = NULL**, l dont know is that a mistake because the command requesting me **grp_sep should be empty**

new_export_url <- kobo_export_create(
  url = "kobo.humanitarianresponse.info",
  uname = "",
  pwd = "",
  assetid = "",
  type = "xls",
  all = "false",
  lang = "_default",
  hierarchy = "false",
  include_grp = "false",
  **grp_sep = NULL**,
  multi_sel = "both",
  fields = NULL,
  media_url = "true",
  sub_ids = NULL,
  qry = NULL,
  flatten = "true",
  **sleep = 120**
)

**Comment by asitav-sen** [comment]
Hi @zxrey ,
Are you using the latest dev version? I updated it few hours back.

**Comment by zxrey** [comment]
@asitav-sen Yes, **kobo_df_download** works but **kobo_export_create** doesn't.  **kobo_df_download** doesn't allow export a xls tipe, so l try to use **kobo_export_create** and is not working.
The message is the same even the sleep timer is high:
Downloading: 1.4 kB     Execution in Progress...Timeout[1] "Export Could Not be created"

**Comment by asitav-sen** [comment]
@zxrey how big is the file? Will it be possible for you to give me temporary access so that I can check specifically and understand what is going wrong?

**Comment by zxrey** [comment]
@asitav-sen  Sure, this is my code:

new_export_url <- kobo_export_create(
  url = "kobo.humanitarianresponse.info",
  uname = "xzrey",
  pwd = "uTT_8ruhQ&_%8UR",
  assetid = "axPwGff9N6ihzkhkSrMQnE",
  type = "xls",
  all = "false",
  lang = "_default",
  hierarchy = "false",
  include_grp = "false",
  grp_sep = NULL,
  multi_sel = "both",
  fields = NULL,
  media_url = "true",
  sub_ids = NULL,
  qry = NULL,
  flatten = "true",
  sleep = 20
)

**Comment by asitav-sen** [comment]
Hi @zxrey ,

I found the issue. Looks like there has been some change in the API, since I wrote the package.

https://kobo.humanitarianresponse.info/api/v2/assets/axPwGff9N6ihzkhkSrMQnE/exports/

You will notice that `include_grp` option does not exist anymore. Hence, for the time being you have to keep using `include_grp="true"`. If you do that and use some group separator, your problem gets solved. And you won't even have to increase the `sleep` value.
Hope it helps.

**Comment by asitav-sen** [comment]
@zxrey Thanks for your support. Happy to help.
 I will close the issue then.
