### ISSUE TITLE
column name with kobo_df_download

### ISSUE THREAD

**Issue by manhnguy** [asitav-sen/KoboconnectR#6]
Hi @asitav-sen,
Thank you very much for your wonderful work. I'm try to use kobo_df_download function but the dataset come out with column names as the labels of the questions instead of the name I gave to them in Kobo. 
Manh

**Comment by asitav-sen** [comment]
Hi @manhnguy ,
Thanks. I could not find the option in API documentation. I have raised the query in the kobotoolbox community [here](https://community.kobotoolbox.org/t/xml-values-and-headers-option-in-api/30172). Once I receive a suitable response, I will update the package accordingly.

**Comment by asitav-sen** [comment]
Hi @manhnguy ,
Looks like you may need to change the language. Can you please try and let me know?

**Comment by asitav-sen** [comment]
Hi @manhnguy ,
Good news. We have the solution. You just need to set the language to `_xml`. Please let me know how it goes!

**Comment by manhnguy** [comment]
It works perfect, wonderful job. thank you very much. I'm trying to figure out how to choose the column in the fields argument.

**Comment by manhnguy** [comment]
Hi @asitav-sen. Thank you so much for your support. Yes, I didn't find the solution. So my data has about 100 columns and when I download, I don't want to download them all, let's say 90. I'm trying to use fields = -c("name1", "name2") but it doesn't work. At the moment, I just use select function in R. It would be great if I can unselect the columns I don't want to have in the download function. It's not big issue though.
