### ISSUE TITLE
kobo_kf_download problem:   Could not resolve host

### ISSUE THREAD

**Issue by andresimi** [asitav-sen/KoboconnectR#8]
Hi, I am also having troubles with kobo_kf_donwnload. But a little different from the previous issues. I am receiving this message:

> df <- kobo_df_download(uname, pwd, assetid, all="false", lang="English (em)", include_grp="false", grp_sep=NULL)
> Error in curl::curl_fetch_memory(url, handle = handle) : 
> Could not resolve host: andresimi
> 

What this could be?

**Comment by asitav-sen** [comment]
Hi @andresimi ,
Sorry about the issue. Are you using any proxy? And is the language correct?

**Comment by andresimi** [comment]
Hi, thank you for your prompt response. No, I am not using proxies and the language is correct. The message persists if I let default language.

**Comment by asitav-sen** [comment]
Hi @andresimi ,
Do the other functions work with same url, userid and password? Also, could you please check if you can access this one from your browser, post login?
``` https://{KF_URL}/api/v2/assets/{ASSET_UID}/exports```

**Comment by andresimi** [comment]
Hello @asitav-sen, thank you for your return.
1. I am able to use kobotools_kpi_data to download data, however, i think it is JSON format. 
2.  I am not sure what to see in the url, so I will post here:
![image](https://user-images.githubusercontent.com/7464255/181844181-726c9d86-1b13-4b54-96fe-d3a73e43b8ff.png)
3. The url parameter is 
url <- "kf.kobotoolbox.org"

Thank you!

**Comment by asitav-sen** [comment]
Hi @andresimi ,
Thank you for your patience. I noticed that the there is no option of "include group" in the API anymore and `group separator` is compulsory. I have changed my code accordingly.
Please download the github version.
`# install.packages("devtools")
devtools::install_github("asitav-sen/KoboconnectR")`

Then rerun the code with `grp_sep="/"`. Hope it helps. Please let me know how it goes.

**Comment by andresimi** [comment]
Hello @asitav-sen!
I updated the package as you instructed, however it had no effect on the problem:

![image](https://user-images.githubusercontent.com/7464255/182151539-45eb3613-8fe2-4d6a-b7e2-e7a018a9062d.png)
Best!

**Comment by asitav-sen** [comment]
Hi @andresimi ,
You need to add the URL parameter as well.
`
kobo_df_download(
url="kf.kobotoolbox.org",
uname = "username",
 pwd="password", 
 assetid = "assetid",
 lang="English (em)")

`
This is because the default value of URL is "kobo.humanitarianresponse.info".

Hope it helps.
